Keep latest tag up to date

diff --git a/.github/workflows/tag.yml b/.github/workflows/tag.yml
--- a/.github/workflows/tag.yml
+++ b/.github/workflows/tag.yml
@@ -15,6 +15,8 @@ jobs:
 
       - name: keep tag
         run: |
-          git tag --delete latest
+          if ! git tag --delete latest 2>/dev/null; then
+            echo "Latest tag not found"
+          fi
           git tag latest
           git push --tags
